src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $texte;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isActive;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ImgName;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getTexte(): ?string
    {
        return $this->texte;
    }

    public function setTexte(string $texte): self
    {
        $this->texte = $texte;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getImgName(): ?string
    {
        return $this->ImgName;
    }

    public function setImgName(string $ImgName): self
    {
        $this->ImgName = $ImgName;

        return $this;
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

class BlogController extends AbstractController
{
    /**
     * @Route("/blog", name="blog")
     */
    public function index()
    {
        $repository = $this->getDoctrine()->getRepository(Article::class);
        $articles = $repository->findAll();

        return $this->render('blog/index.html.twig', [
            'articles' => $articles,
        ]);
    }

    /**
     * @Route("/new", name="newArticle")
     */
    public function newArticle(Request $request)
    {
        $article = new Article();

        $entityManager = $this->getDoctrine()->getManager();
        $form = $this->createForm(ArticleFormType::class, $article);
        $form->handleRequest(($request));

        if ($form->isSubmitted() && $form->isValid()) {

            // ajout Image
            $imgFile = $form['ImgName']->getData();
            if ($imgFile) {
                $originalFilename = pathinfo($imgFile->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $imgFile->guessExtension();
                // Move the file to the directory where brochures are stored
                try {
                    $imgFile->move(
                        $this->getParameter('imgArticle_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
                $article->setImgName($newFilename);
                //EO

                $article->setCreatedAt(new \DateTime());
                $article->setIsActive(true);

                $entityManager->persist($article);

                $entityManager->flush();

                $this->addFlash(
                    'success',
                    ''
                );

                return $this->redirectToRoute('blog');
            }
        }
        return $this->render('blog/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/one/{articleId}", name="oneArticle")
     */
    public function oneArticle($articleId)
    {
        $repository = $this->getDoctrine()->getRepository(Article::class);
        $article = $repository->find($articleId);

        return $this->render('blog/one.html.twig', [
            'article' => $article
        ]);
    }
}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Actualité{% endblock %}

{% block body %}
	<section id="main" class="container">
		<header>
			<h2>Actualité</h2>
			{% if app.user is not null  %}
				<a href="{{path('newArticle')}}">
					<i class="fas fa-plus icon-edit" ></i>
				</a>
			{% endif %}
		</header>
		{% for article in articles %}

			<section class="box blog-list">
				<h4>{{article.title}}</h4>
				<p>
					<!-- Affichage Image -->
					<span class="image left img-article"><img src="{{ asset('uploads/Articles/'~ article.imgName) }}" alt="" /></span>
					{{article.texte}}
				</p>
				<ul class="actions special">
					<li><a href="{{path('oneArticle', {articleId: article.id})}}" class="button alt">Lire plus</a></li>
				</ul>
			</section>
		{% endfor %}

	</section>
{% endblock %}

templates/blog/new.html.twig
{% extends 'base.html.twig' %}
{% block title %}Nouvel article{% endblock %}

{% block body %}
	<section id="main" class="container medium">
		<header>
			<h2>Création d'un article</h2>
		</header>
		<div class="box">
			{{ form(form) }}
		</div>
		
{% endblock %}

templates/blog/one.html.twig
{% extends 'base.html.twig' %}
{% block title %}Article{% endblock %}

{% block body %}

<!-- Main -->
	<section id="main" class="container">
		<header>
			<h2>{{article.title}}</h2>
			<p>A generic page for every non-generic situation.</p>
		</header>
		<div class="box">
			<span class="image featured"><img src="img/pic01.jpg" alt="" /></span>
			<h3>{{article.title}}</h3>
			<p>{{article.texte}}</p>
		</div>
	</section>
{% endblock %}